# Generated by Django 5.2.2 on 2025-07-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('lab_id', models.IntegerField()),
                ('faculty_id', models.IntegerField()),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(max_length=100)),
                ('topic_covered', models.TextField()),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('location_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('total_sessions', models.IntegerField()),
                ('attended_sessions', models.IntegerField()),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('attendance_date', models.DateField()),
                ('marked_at', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('location_data', models.JSONField()),
                ('device_info', models.TextField()),
                ('verification_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendanceapp.attendancesession')),
            ],
        ),
    ]
