# Generated by Django 5.2.2 on 2025-07-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationSchedule',
            fields=[
                ('exam_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_id', models.IntegerField()),
                ('exam_type', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('exam_rules', models.JSONField()),
                ('time_table', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('semester_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grade_points_earned', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('result_status', models.CharField(max_length=50)),
                ('declared_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseExamination',
            fields=[
                ('course_exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('lab_id', models.IntegerField(blank=True, null=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.CharField(max_length=255)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_minutes', models.IntegerField()),
                ('venue', models.CharField(max_length=255)),
                ('invigilators', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exams', to='examinationapp.examinationschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('theory_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('practical_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('internal_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(max_length=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('result_status', models.CharField(max_length=50)),
                ('result_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinationapp.courseexamination')),
            ],
        ),
    ]
