# Generated by Django 5.2.2 on 2025-07-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=50)),
                ('theory_credits', models.IntegerField()),
                ('practical_credits', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('prerequisites', models.JSONField()),
                ('learning_outcomes', models.JSONField()),
                ('syllabus_url', models.URLField()),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('program_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('program_type', models.CharField(max_length=50)),
                ('degree_type', models.CharField(max_length=50)),
                ('duration_semesters', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('eligibility_criteria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission_requirements', models.JSONField()),
                ('curriculum_structure', models.JSONField()),
                ('accreditation', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(max_length=20, unique=True)),
                ('lab_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
                ('equipment_required', models.JSONField()),
                ('experiment_list', models.JSONField()),
                ('lab_manual_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('semester_name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField()),
                ('min_credits', models.IntegerField()),
                ('max_credits', models.IntegerField()),
                ('semester_structure', models.JSONField()),
                ('academic_year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.program')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.semester'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
                ('syllabus_content', models.JSONField()),
                ('reference_materials', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.course')),
            ],
        ),
    ]
