# Generated by Django 5.2.2 on 2025-07-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('semester_id', models.IntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('role_type', models.CharField(max_length=50)),
                ('teaching_load', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('registration_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_date', models.DateField()),
                ('last_date', models.DateField()),
                ('fee_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
                ('batch_year', models.CharField(max_length=10)),
                ('enrollment_status', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField()),
                ('expected_graduation', models.DateField()),
                ('admission_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('registration_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('additional_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semesterregistration')),
            ],
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.studentprogramenrollment'),
        ),
    ]
